### ISSUE TITLE
Crash app because "No static field recyclerview of type I in class Ldroidninja/filepicker/R$id"

### ISSUE THREAD

**Issue by HayTran** [DroidNinja/Android-FilePicker#109]
This message below is track trace I received before app crashing

> E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: mnslab.isleep, PID: 22510
                                                               java.lang.NoSuchFieldError: No static field recyclerview of type I in class Ldroidninja/filepicker/R$id; or its superclasses (declaration of 'droidninja.filepicker.R$id' appears in /data/app/mnslab.isleep-Fof5goko8M7Oavpg7Dmexw==/split_lib_slice_0_apk.apk)
                                                                   at droidninja.filepicker.fragments.MediaFolderPickerFragment.initView(MediaFolderPickerFragment.java:104)
                                                                   at droidninja.filepicker.fragments.MediaFolderPickerFragment.onViewCreated(MediaFolderPickerFragment.java:100)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                   at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:687)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
                                                                   at android.view.View.measure(View.java:21998)
                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)

**Comment by DroidNinja** [comment]
This might be build and clean issue. Clean and rebuild project and comment if this issue still persists.
