### ISSUE TITLE
Binary XML file line #6: Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by kncxstudio** [DroidNinja/Android-FilePicker#11]
FATAL EXCEPTION: main
                                                                          Process: com.yuehu.cola.projectcola, PID: 6757
                                                                          android.view.InflateException: Binary XML file line #6: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                              at droidninja.filepicker.adapters.PhotoGridAdapter.onCreateViewHolder(PhotoGridAdapter.java:42)
                                                                              at droidninja.filepicker.adapters.PhotoGridAdapter.onCreateViewHolder(PhotoGridAdapter.java:24)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5833)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5057)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                              at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                              at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1556)
                                                                              at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:666)
                                                                              at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:598)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                              at android.view.View.layout(View.java:15671)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                          	at android.view.
08

**Comment by kncxstudio** [comment]
I found my error reason.I didn't call Fresco.initialize().BTW,can I use Glide instead of Fresco?

**Comment by DroidNinja** [comment]
Currently, Fresco is dependency for showing images efficiently. But, I will remove this dependency or provide support for other image caching libraries in upcoming version. Thanks!

**Comment by kncxstudio** [comment]
Thanks！

**Comment by k0shk0sh** [comment]
Its due to that, you are defining custom Application in your manifest, so then we try to use our own App, gradle throws an error to replace your application name tag, then in this case fresco is not being initialised.
What i suggest you to do is, make singleton class  to initials the Fresco or do it within the Activity. 
since this issue is never being solved, i think it shouldn't be closed. thanks

**Comment by DroidNinja** [comment]
@k0shk0sh I have removed dependency of application class in library and has initialised fresco in activity.

**Comment by k0shk0sh** [comment]
@DroidNinja  i guess what you are doing is wrong tho, you are initialising the library every time the activity `onCreate` is being called, you should use `if(savedInstance == null) {//initialise fresco}` to avoid initialising multiple times.

**Comment by DroidNinja** [comment]
@k0shk0sh  Its savedInstance is never saved, as I am finishing the activity when the user clicks on Done button. I think, savedInstance only works when activity is finished by android OS.

**Comment by k0shk0sh** [comment]
what about rotating the screen?
