### ISSUE TITLE
Crashing SecurityException: Need to handle permissions

### ISSUE THREAD

**Issue by sreejithbnaick** [DroidNinja/Android-FilePicker#118]
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                      Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=31352, uid=10108 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                         at android.os.Parcel.readException(Parcel.java:1684)
                                                                         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                         at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                         at android.content.ContentResolver.query(ContentResolver.java:532)
                                                                         at android.content.ContentResolver.query(ContentResolver.java:474)
                                                                         at droidninja.filepicker.cursors.DocScannerTask.doInBackground(DocScannerTask.java:53)
                                                                         at droidninja.filepicker.cursors.DocScannerTask.doInBackground(DocScannerTask.java:25)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                         at java.lang.Thread.run(Thread.java:761)`

**Comment by DroidNinja** [comment]
Yeah you need to handle security permission manually in your app. Currently library doesn't support that. You should check sample. I will try to add this functionality in upcoming version.
