### ISSUE TITLE
com.droidninja:filepicker:2.1.1 .pickPhoto(this) Error with Glide 4.4.0

### ISSUE THREAD

**Issue by accessible89** [DroidNinja/Android-FilePicker#121]
Hi! Thanks for libs! Great job. 

I have Error on pickPhoto, when use  Glide 4.4.0, but with using Glide 4.0.0 it's all right.
Error log:
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/ru.b2app.app.shop.oshishacc-1/split_lib_dependencies_apk.apk)
                                                                                 at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:77)
                                                                                 at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:24)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                                 at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                                 at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
                                                                                 at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1691)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1467)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                                 at android.view.View.layout(View.java:16992)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                             	at android.widget.FrameLayout.layoutChildren(FrameLayout.j

**Comment by erdemtpz** [comment]
Same issue.

**Comment by DroidNinja** [comment]
Build is running fine on my machine.This has been asked multiple times in here and dozen other forums that are using glide.  I can't seem to find any issue. :(  But Can you please check:
1. Not using multiple glide versions in different modules.
2. May be there is some multidex problems.
3. Or Do you have any weird proguard rules set for glide?

**Comment by accessible89** [comment]
1. Not using multiple glide versions in different modules. 
Before using FilePicker I use glide v.3+.  But now I clean all versions and using 4.4.0 or 4.0.0 
2. May be there is some multidex problems. (Can't check, because not understand, how check this)
3. Or Do you have any weird proguard rules set for glide?
I use your proguard rules from README

**Comment by orgil1230** [comment]
Same issue

**Comment by Scienticious** [comment]
Same issue

**Comment by aykutuludag** [comment]
same issue

**Comment by sunilsoniudaipur** [comment]
same issue tried to use the different version of the Glide.

**Comment by mishu-bilfinger** [comment]
Same issue :(

**Comment by DroidNinja** [comment]
Guys..Can you tell me are you able to run the sample in this project without any issue?

**Comment by mishu-bilfinger** [comment]
Now working with latest glide with latest droidninja:filepicker . thanks :)

compile 'com.droidninja:filepicker:2.1.2'
compile 'com.github.bumptech.glide:glide:4.5.0'`

**Comment by erdemtpz** [comment]
Yes, now working. 
compile 'com.droidninja:filepicker:2.1.2'
compile 'com.github.bumptech.glide:glide:4.5.0'
