### ISSUE TITLE
NoClassDefFound Error : App Crashed with the implementation of library 

### ISSUE THREAD

**Issue by lakshyapunhani** [DroidNinja/Android-FilePicker#124]
01-13 15:45:58.598 22703-22703/com.example.wuntu.billstore E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.wuntu.billstore, PID: 22703
                                                                             java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
                                                                                 at droidninja.filepicker.fragments.MediaFolderPickerFragment.onCreate(MediaFolderPickerFragment.java:93)
                                                                                 at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                                 at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
                                                                                 at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
                                                                                 at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
                                                                                 at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                                                                                 at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                                 at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                                                                                 at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:916)
                                                                                 at android.view.View.measure(View.java:21307)
                                                                                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
                                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1697)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1952)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
01-13 15:45:58.601 22703-22703/com.example.wuntu.billstore E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:705)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:640)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6816)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathList[[zip file "/data/app/com.example.wuntu.billstore-1/base.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.wuntu.billstore-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.wuntu.billstore-1/lib/arm, /system/lib, /vendor/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                 	... 63 more

**Comment by DroidNinja** [comment]
@lakshyapunhani Are you able to run sample project successfully?

**Comment by lakshyapunhani** [comment]
In the implementation please write to add glide library as well. It was crashing because glide was not there.
Need to add 
compile 'com.github.bumptech.glide:glide:4.5.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.5.0'

**Comment by DroidNinja** [comment]
But it is already there in the filepicker module.

**Comment by lakshyapunhani** [comment]
I too checked the file picker module and see the glide dependency there and included glide dependency with annotation processor then it went smoother.

**Comment by DroidNinja** [comment]
So its all fixed now?

**Comment by lakshyapunhani** [comment]
Yes
