### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by zeevy** [DroidNinja/Android-FilePicker#127]
I am using the file picker in v4 fragment.
version 2.1.0 is working fine.
version 2.1.1 not working.
version 2.1.2 not working.
gives toast message "Storage permission is need to access the files" although permission is granted.

**Comment by DroidNinja** [comment]
@zeevy Not able to replicate this bug in sample. Are you getting this in sample?

**Comment by zeevy** [comment]
I am using it here https://github.com/zeevy/grblcontroller

**Comment by DroidNinja** [comment]
Its working fine. I tried to run your code. Is there any specific use case? 
See this vid:https://drive.google.com/file/d/1c7OONSbUy6mj3BurHAnQyBfX_pZArV8-/view

**Comment by zeevy** [comment]
@DroidNinja did you changed  the filepicker lib version in gradle ?
I still gets this error when i used version 2.1.3 in android 8.0.0
https://www.youtube.com/watch?v=Xm_HrNekE-w

And got Exception in android 5.1

02-12 09:55:09.016 5073-5073/in.co.gorest.grblcontroller E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: in.co.gorest.grblcontroller, PID: 5073
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{in.co.gorest.grblcontroller/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2348)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5351)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
                                                                            Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:201)
                                                                               at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
                                                                               at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.java:26)
                                                                               at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.java:28)
                                                                               at android.app.Activity.performCreate(Activity.java:6012)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5351) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by sidhuparas** [comment]
@zeevy @DroidNinja I have the same issue. I upgraded from v2.1.1 to v2.1.3. So maybe it started with v2.1.2. The permission is granted but it says Storage permission is required to access the files. My app is targeted at SDK version 27.

To confirm the issue is with the library itself, I downgraded to v2.1.1 and it worked fine. The document dialog was opened to pick the files. Then again upgraded to v2.1.3 and got the same error. I have also tried resetting app data but same error.

**Comment by DroidNinja** [comment]
@zeevy @sidhuparas I still haven't able to replicate that Storage permission bug even I checkout your code. Is this bug happening in Filepicker's sample too at your end? I need your help on this.
 And about exception in android 5.1 is because I have changed FilePicker activity theme. You need to style FilePicker by inheriting its theme and make the required changes like It is done in app sample. 
```xml
 <style name="FilePickerTheme" parent="LibAppTheme">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="PickerTabLayout" parent="Widget.Design.TabLayout">
        <item name="tabBackground">@color/colorPrimary</item>
        <item name="tabSelectedTextColor">@android:color/white</item>
        <item name="tabGravity">fill</item>
        <item name="tabMaxWidth">0dp</item>
    </style>
```
See above code, It is inheriting  FilePicker's `LibAppTheme` and overriding with respective colors.

**Comment by sidhuparas** [comment]
@DroidNinja Let me try it in a new sample project. But till then, you can check my app: https://github.com/sidhuparas/PDFPinner Clone it, run it and press "Choose Files...". This should help in reproducing the problem.

**Comment by sidhuparas** [comment]
I tried it on a new project and probably found the problem.
```    
private void choosePDF() {
        String[] pdf = {".pdf"};
        FilePickerBuilder.getInstance()
                .setActivityTheme(R.style.AppTheme)
                .addFileSupport("PDF", pdf)
                .enableDocSupport(false)
                .enableSelectAll(true)
                .showFolderView(false)
                .pickFile(MainActivity.this);
    }
```

I tried it in Android 8.1 with targetSDK 27. Initially, the app crashed with following error:

```
02-15 08:03:14.816 9768-9768/com.parassidhu.morningmotivation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.parassidhu.morningmotivation, PID: 9768
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.parassidhu.morningmotivation/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
                                                                                    at android.app.ActivityThread.-wrap18(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                 Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:201)
                                                                                    at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
                                                                                    at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.java:26)
                                                                                    at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.java:28)
                                                                                    at android.app.Activity.performCreate(Activity.java:6999)
                                                                                    at android.app.Activity.performCreate(Activity.java:6990)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699) 
                                                                                    at android.app.ActivityThread.-wrap18(Unknown Source:0) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

I then changes styles.xml from:

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

</resources>
```

to:

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

</resources>
```

It worked. The doc picker opened with some visual issues like no shadow of toolbar. Hope you can reproduce the issue now :)

**Comment by zeevy** [comment]
Hi Arun,
The example code seems to be working fine.
But i still gets the error on simple app (android 8.0)

here are the files:
build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "in.co.gorest.filepicker"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.droidninja:filepicker:2.1.3'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
```
Activity
```
package in.co.gorest.filepicker;

import android.Manifest;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.Toast;

import droidninja.filepicker.FilePickerBuilder;

public class MainActivity extends AppCompatActivity {

    private final  int REQUEST_READ_PERMISSIONS = 10;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        Button button = findViewById(R.id.pick_file);
        button.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View v){
                if(hasExternalStorageReadPermission()){
                    getFilePicker();
                }else{
                    askExternalReadPermission();
                }
            }
        });

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }


    private Boolean hasExternalStorageReadPermission(){
        Boolean hasPermission = true;
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
                hasPermission = false;
            }
        }
        return hasPermission;
    }

    private void getFilePicker(){
        String[] gcodeTypes = {".tap",".gcode", ".nc", ".ngc"};
        FilePickerBuilder.getInstance().setMaxCount(1)
                .setActivityTheme(R.style.FilePickerTheme)
                .addFileSupport(".tap | .gcode | .nc | .ngc", gcodeTypes)
                .enableDocSupport(false)
                .pickFile(this);
    }


    private void askExternalReadPermission(){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, REQUEST_READ_PERMISSIONS);
        }else{
            Toast.makeText(this, "No permission", Toast.LENGTH_LONG).show();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if(requestCode == REQUEST_READ_PERMISSIONS){
            if(grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED){
                getFilePicker();
            }else{
                Toast.makeText(this, "No permission", Toast.LENGTH_LONG).show();
            }
        }
    }


}
```

**Comment by zeevy** [comment]
For me this problem is coming only in Android 8.0
In Android 5.1 2.1.3 version is working fine

**Comment by DroidNinja** [comment]
@zeevy Okay I get it. I think the bug is you are checking for `READ_EXTERNAL_STORAGE` but filepicker requires `WRITE_EXTERNAL_STORAGE`.

**Comment by zeevy** [comment]
Oh ok, why would it require write permission as it is just a file picker.

**Comment by sidhuparas** [comment]
@DroidNinja Have you tried cloning and trying my project (link above)? I'm just asking for `WRITE_EXTERNAL_STORAGE` permission but still it doesn't work.

**Comment by zeevy** [comment]
@sidhuparas 
in my case adding "WRITE_EXTERNAL_STORAGE" fixed the problem.
