### ISSUE TITLE
Not able to Pick Image in Blackberry - STV100-1: NullPointerException

### ISSUE THREAD

**Issue by mghisham** [DroidNinja/Android-FilePicker#143]
I am using the file picker version 2.1.0 in v4 fragment.
Exception when starting FilePickerActivity.
Receving this error

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
	at droidninja.filepicker.cursors.loadercallbacks.PhotoDirLoaderCallbacks.onLoadFinished(PhotoDirLoaderCallbacks.java:62)
	at droidninja.filepicker.cursors.loadercallbacks.PhotoDirLoaderCallbacks.onLoadFinished(PhotoDirLoaderCallbacks.java:27)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:977)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)`

**Comment by DroidNinja** [comment]
Fixed in 2.1.4
