### ISSUE TITLE
Not Able to Select Image/Photo

### ISSUE THREAD

**Issue by aadeez** [DroidNinja/Android-FilePicker#146]
This Exception occur while selecting the image
03-05 15:54:42.107 2900-2900/com.bm.printit E/RecyclerView: No adapter attached; skipping layout
03-05 15:54:42.439 2900-2900/com.bm.printit E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.bm.printit, PID: 2900
                                                              java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.bm.printit-2/base.apk:classes53.dex)
                                                                  at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:71)
                                                                  at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:24)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:18878)
03-05 15:54:42.439 2900-2900/com.bm.printit E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at com.android.internal.policy.DecorView.onLayout(DecorView.java:934)
                                                                  at android.view.View.layout(View.java:18878)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5953)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2684)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by vinayakmestri** [comment]
getting same error

**Comment by DroidNinja** [comment]
This is glide issue and have been raised many times. I have updated Glide version to 4.6.1. Try it with v2.1.4.

**Comment by jianiuqi** [comment]
I tryed version 2.1.4, but the problem still exists.

**Comment by andkishor** [comment]
I tried with latest version 2.1.5 but still i am getting same issue.

System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
System.err:     at droidninja.filepicker.fragments.MediaFolderPickerFragment.onCreate(MediaFolderPickerFragment.java:94)
System.err:     at android.support.v4.app.Fragment.performCreate(Fragment.java:2226)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
System.err:     at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
System.err:     at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:973)
System.err:     at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:97)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2197)
System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err:     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
System.err:     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
System.err:     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1239)
System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1087)
System.err:     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1613)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
System.err:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1117)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:642)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
System.err:     at android.view.View.measure(View.java:19857)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:621)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathLi
st[[zip file "/data/app/org.nativescript.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.demo-1/l
ib/x86, /data/app/org.nativescript.demo-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 61 more
ActivityManager: Process org.nativescript.demo (pid 6251) has died
ActivityManager: cleanUpApplicationRecord -- 6251

**Comment by Prudyeot** [comment]
same problem, i am trying to display picked photos in a fragment, please help.

**Comment by jorgeblacio** [comment]
I had the same error, I managed to make it work with glide 4.0.0
