### ISSUE TITLE
NullPointerException: android.support.v7.widget.SearchView.setOnQueryTextListener

### ISSUE THREAD

**Issue by zeevy** [DroidNinja/Android-FilePicker#156]
This error comes only in release build, debug build works fine. Have any idea where is the problem?
Using version 2.1.4
```
04-09 10:19:51.214 31369-31369/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.co.gorest.grblcontroller, PID: 31369
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$c)' on a null object reference
        at droidninja.filepicker.c.b.a(DocFragment.java:139)
        at android.support.v4.app.h.b(Fragment.java:2450)
        at android.support.v4.app.n.a(FragmentManager.java:3296)
        at android.support.v4.app.h.b(Fragment.java:2453)
        at android.support.v4.app.n.a(FragmentManager.java:3296)
        at android.support.v4.app.k.a(FragmentController.java:322)
        at android.support.v4.app.i.onCreatePanelMenu(FragmentActivity.java:365)
        at android.support.v7.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.f$a.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
        at android.support.v7.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.m.i(ToolbarActionBar.java:454)
        at android.support.v7.app.m$1.run(ToolbarActionBar.java:55)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:710)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6637)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by zeevy** [comment]
Issue occurs if Proguard  is enabled.
can be fixed by adding this to proguard rules
```
-keep class android.support.v7.widget.SearchView { *; }
```
