### ISSUE TITLE
Library doesn't work with androidx dependencies

### ISSUE THREAD

**Issue by izBasit** [DroidNinja/Android-FilePicker#169]
I recently updated the dependencies of my project and this is what error I get.
Stacktrace
`java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Lcom/google/android/material/tabs/TabLayout$OnTabSelectedListener;)V in class Lcom/google/android/material/tabs/TabLayout; or its super classes (declaration of 'com.google.android.material.tabs.TabLayout' appears in /data/app/..)
        at droidninja.filepicker.utils.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:351)
        at droidninja.filepicker.utils.TabLayoutHelper.<init>(TabLayoutHelper.java:100)
        at droidninja.filepicker.fragments.DocPickerFragment.setUpViewPager(DocPickerFragment.java:145)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.java:85)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.java:81)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:610)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
        at android.app.Activity.performStart(Activity.java:7056)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2874)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by izBasit** [comment]
@aayushsingla I forked the project and refactored.

**Comment by jasonivers** [comment]
I get a similar error for using android.support.v4 stuff:

```
    java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.enginato.chat-1/split_lib_dependencies_apk.apk)
        at droidninja.filepicker.utils.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:351)
        at droidninja.filepicker.utils.TabLayoutHelper.<init>(TabLayoutHelper.java:100)
        at droidninja.filepicker.fragments.DocPickerFragment.setUpViewPager(DocPickerFragment.java:145)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.java:85)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.java:81)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
        at android.app.Activity.performStart(Activity.java:6972)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by MubeenMajeed** [comment]
implementation 'com.google.android.material:material:1.0.0-rc01'

**Comment by Peter-Emad** [comment]
@MubeenMajeed @izBasit how did you fix it?

**Comment by sandysultan** [comment]
> I recently updated the dependencies of my project and this is what error I get.
> Stacktrace
> `java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Lcom/google/android/material/tabs/TabLayout$OnTabSelectedListener;)V in class Lcom/google/android/material/tabs/TabLayout; or its super classes (declaration of 'com.google.android.material.tabs.TabLayout' appears in /data/app/..) at droidninja.filepicker.utils.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:351) at droidninja.filepicker.utils.TabLayoutHelper.<init>(TabLayoutHelper.java:100) at droidninja.filepicker.fragments.DocPickerFragment.setUpViewPager(DocPickerFragment.java:145) at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.java:85) at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.java:81) at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471) at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802) at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623) at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410) at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365) at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272) at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271) at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227) at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:610) at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413) at android.app.Activity.performStart(Activity.java:7056) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2874) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989) at android.app.ActivityThread.-wrap11(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6753) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

which dependencies affect this?

**Comment by pacosta** [comment]
> I will upgrade it once stable release of 3.2 is out.

3.2 out, will you release an update?

**Comment by SUBINPTPM** [comment]
> I will upgrade it once a stable release of 3.2 is out.

please release updated version

**Comment by masehitam** [comment]
any solution yet ?

**Comment by nguyencongbinh** [comment]
Hello author,

Please update the library to solve this issue. Thank you so much.

**Comment by batorshih** [comment]
what library or program should i update for 3.2

**Comment by karanianandkumar** [comment]
Any update on this issues

**Comment by NichetechInovation** [comment]
> implementation 'com.google.android.material:material:1.0.0-rc01'

@MubeenMajeed thanks for solutions.

**Comment by xylophone** [comment]
implementation 'com.droidninja:filepicker:2.2.1'
