### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException - Binary XML file line #1: invalid drawable tag vector

### ISSUE THREAD

**Issue by Argonisius** [DroidNinja/Android-FilePicker#180]
Not 100 % sure it's a FilePicker issue, but it seems to be coming from its code:

```
# OS Version: 4.4.2
# Device: Galaxy Young2
# RAM Free: 21.4%
# Disk Free: 30%

#0. Crashed: main
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:51)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6748)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5929)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3595)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4148)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2379)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2087)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1263)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6611)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5641)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
       at dalvik.system.NativeStart.main(NativeStart.java)

--

Fatal Exception: android.view.InflateException: Binary XML file line #8: Error inflating class ImageView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:51)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6748)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5929)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3595)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4148)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2379)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2087)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1263)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6611)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5641)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by android.content.res.Resources$NotFoundException: File res/drawable/image_placeholder.xml from drawable resource ID #0x7f0700a8
       at android.content.res.Resources.loadDrawable(Resources.java:3430)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.view.View.<init>(View.java:3704)
       at android.widget.ImageView.<init>(ImageView.java:127)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
       at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
       at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1263)
       at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1313)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:51)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6748)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5929)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3595)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4148)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2379)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2087)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1263)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6611)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5641)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
       at android.content.res.Resources.loadDrawable(Resources.java:3426)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.view.View.<init>(View.java:3704)
       at android.widget.ImageView.<init>(ImageView.java:127)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
       at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
       at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1263)
       at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1313)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:51)
       at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6748)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5929)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3595)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4148)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15639)
       at android.view.ViewGroup.layout(ViewGroup.java:4884)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2379)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2087)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1263)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6611)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5641)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Sunkari16** [comment]
We are also facing same issue.
