### ISSUE TITLE
Android 8.0.0 camera crash.

### ISSUE THREAD

**Issue by aykutuludag** [DroidNinja/Android-FilePicker#181]
Hi! I got following error when I press the camera button in the photo filepicker. I checked twice the app has both STORAGE and CAMERA permission.

`    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Pictures/JPEG_1532553902602.jpg
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at droidninja.filepicker.utils.ImageCaptureManager.dispatchTakePictureIntent(ImageCaptureManager.java:71)
        at droidninja.filepicker.fragments.MediaFolderPickerFragment.onCameraClicked(MediaFolderPickerFragment.java:205)
        at droidninja.filepicker.adapters.FolderGridAdapter$2.onClick(FolderGridAdapter.java:99)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24708)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by GauravRana** [comment]
try disabling it 
`FilePickerBuilder.getInstance().enableCameraSupport(false);`

if you don't require

**Comment by matiasgitl** [comment]
@aykutuludag did you finde any solutions? I have the problem :)
