### ISSUE TITLE
crash on document attachment 

### ISSUE THREAD

**Issue by pouriabagheri** [DroidNinja/Android-FilePicker#182]
when parent project gradle set to minfy enabled it crashes on file attachment activity
```
 buildTypes {
        release {
            minifyEnabled true
            proguardFiles fileTree(dir: 'proguard', include: ['*.pro']).asList().toArray()
            proguardFile getDefaultProguardFile('proguard-android.txt')
            testProguardFile 'proguard-project-test.pro'
            signingConfig signingConfigs.myApp

        }
```
**Error Log:** 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$c)' on a null object reference
                                                     at droidninja.filepicker.fragments.a.onCreateOptionsMenu(SourceFile:141)
                                                     at android.support.v4.app.Fragment.performCreateOptionsMenu(SourceFile:2450)
                                                     at android.support.v4.app.o.a(SourceFile:3296)
                                                     at android.support.v4.app.Fragment.performCreateOptionsMenu(SourceFile:2453)
                                                     at android.support.v4.app.o.a(SourceFile:3296)
                                                     at android.support.v4.app.l.a(SourceFile:322)
                                                     at android.support.v4.app.j.onCreatePanelMenu(SourceFile:365)
                                                     at android.support.v7.view.i.onCreatePanelMenu(SourceFile:93)
                                                     at android.support.v7.app.g$b.onCreatePanelMenu(SourceFile:332)
                                                     at android.support.v7.view.i.onCreatePanelMenu(SourceFile:93)
                                                     at android.support.v7.app.n.k(SourceFile:454)
                                                     at android.support.v7.app.n$1.run(SourceFile:55)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:710)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                     at android.os.Handler.handleCallback(Handler.java:790)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:172)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6590)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by pouriabagheri** [comment]
issue #156 has the solution
