### ISSUE TITLE
Can't use a file from Dropbox

### ISSUE THREAD

**Issue by mpardalm** [DroidNinja/Android-FilePicker#184]
I'm trying to get a document from dropbox but it throws me this error on my Logcat:

>`FATAL EXCEPTION: main
                                                                           Process: ***, PID: 13537
                                                                           java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=235, result=-1, data=Intent { dat=content://com.dropbox.android.FileCache/filecache/a6ba6acb-77e1-4cf5-af0f-bac5647d3860 typ=application/pdf flg=0x3 }} to activity {***/droidninja.filepicker.FilePickerActivity}: java.lang.SecurityException: No persistable permission grants found for UID 10692 and Uri 0 @ content://com.dropbox.android.FileCache/filecache/a6ba6acb-77e1-4cf5-af0f-bac5647d3860
                                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
                                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
                                                                               at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                               at android.os.Looper.loop(Looper.java:156)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                            **Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10692 and Uri 0 @ content://com.dropbox.android.FileCache/filecache/a6ba6acb-77e1-4cf5-af0f-bac5647d3860**
                                                                               at android.os.Parcel.readException(Parcel.java:1665)
                                                                               at android.os.Parcel.readException(Parcel.java:1618)
                                                                               at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4856)
                                                                               at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1832)
                                                                               at droidninja.filepicker.FilePickerActivity.onActivityResult(FilePickerActivity.java:155)
                                                                               at android.app.Activity.dispatchActivityResult(Activity.java:7188)
                                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)`

Can anyone help me to solve this issue?

**Comment by HBiSoft** [comment]
@mpardalm can you please explain how you resolved this issue?
