### ISSUE TITLE
open  FilePickerActivity

### ISSUE THREAD

**Issue by Jay-YaoJie** [DroidNinja/Android-FilePicker#190]
09-17 16:55:28.852 27771-27771/com.xc.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xc.app, PID: 27771
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xc.app/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640)
        at android.app.ActivityThread.access$800(ActivityThread.java:182)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5682)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:201)
        at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:129)
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.java:26)
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:6161)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
        at android.app.ActivityThread.access$800(ActivityThread.java:182) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by InesRo** [comment]
I have the same problem and this solution is not working for me :/
