### ISSUE TITLE
Failed to open FilePickerActivity

### ISSUE THREAD

**Issue by iamwee** [DroidNinja/Android-FilePicker#191]
Failed to open FilePickerActivity cause: 

java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.example.testBrowseFile-r__hGGEYC6uVnc7oMFigrg==/split_lib_dependencies_apk.apk)
        at droidninja.filepicker.utils.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:351)
        at droidninja.filepicker.utils.TabLayoutHelper.<init>(TabLayoutHelper.java:100)
        at droidninja.filepicker.fragments.DocPickerFragment.setUpViewPager(DocPickerFragment.java:145)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.java:85)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.java:81)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I guess these problem might not update android support library to latest version e.q. 28.0.0-rc2, so i tried to add gradle script from below to exclude android support library inside filePicker library and then use support library latest version but still cannot solved these problem. 

`implementation('com.droidninja:filepicker:2.1.5') {
        exclude group: 'com.android.support', module: 'design'
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
}`

if anyone found these problem, please tell me how to solve it

Thank you

**Comment by rahulkhot123** [comment]
how to solve this problem

**Comment by androidovshchik** [comment]
the same issue

**Comment by toidv** [comment]
Same here 
```
implementation "com.droidninja:filepicker:$filePickerVersion"
ext {
    supportLibVersion = '2.1.5'
```

**Comment by karanianandkumar** [comment]
any update on this issue, please.

**Comment by PragyaSingla** [comment]
same issue is coming. Please update on this

**Comment by dhh940827** [comment]
same issue is coming. Please update on this

**Comment by jitarun** [comment]
any updates?
