### ISSUE TITLE
java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

### ISSUE THREAD

**Issue by Jay-YaoJie** [DroidNinja/Android-FilePicker#193]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xc.app/droidninja.filepicker.FilePickerActivity}:
  java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
        at android.app.ActivityThread.access$800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5113)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
        at android.support.v7.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:345)
        at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:130)
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.java:26)
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:5245)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
        at android.app.ActivityThread.access$800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5113) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
        at dalvik.system.NativeStart.main(Native Method) 
09-30 16:20:58.268 30940-30940/com.xc.app I/Process: Sending signal. PID: 30940 SIG: 9
09-30 16:20:58.268 949-1380/? W/ActivityManager:   Force finishing activity com.xc.app/droidninja.filepicker.FilePickerActivity
09-30 16:20:58.268 949-1380/? W/ActivityManager:   Force finishing activity com.xc.app/.ui.activity.UpLoadStoreResActivity

**Comment by matteogabella** [comment]
just add in AppTheme, in you styles.xml

        <item name="windowActionBar">true</item>
        <item name="windowNoTitle">true</item>
