### ISSUE TITLE
App crash when try to Pick a File when I am  using 28.0.0 (compileSdkversion & targetSdkVersion)

### ISSUE THREAD

**Issue by crismaver1993** [DroidNinja/Android-FilePicker#194]
![capture](https://user-images.githubusercontent.com/20066286/46416363-fdf3e080-c6ec-11e8-8f73-a83cacb52532.PNG)

 compileSdkVersion 28
buildToolsVersion '28.0.3'
targetSdkVersion 28

If I downgrade it to 27 

compileSdkVersion 27
    buildToolsVersion '27.0.3'
 targetSdkVersion 27

it works perfectly

**Comment by KhanStan99** [comment]
Same error with me. I rolled back to 27.1.1 to make it work. Hope he fixes this ASAP.

**Comment by KhanStan99** [comment]
Only file picker crashes. Photo picker works fine for me.

**Comment by datMaster** [comment]
I have the same issue.

**Comment by datMaster** [comment]
Change compileSdkVersion to version 28 and then override method createDocumentType of DocScannerTask.java like this

```
private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {
    HashMap<FileType, List<Document>> documentMap = new HashMap<>();

    for (final FileType fileType : fileTypes) {
      ArrayList<Document> documentListFilteredByType = new ArrayList<>();
      for (Document doc: documents) {
        if (doc.isThisType(fileType.extensions)) {
          documentListFilteredByType.add(doc);
        }
      }
      if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
      documentMap.put(fileType, documentListFilteredByType);
    }

    return documentMap;
  }

```

**Comment by crismaver1993** [comment]
> Change compileSdkVersion to version 28 and then override method createDocumentType of DocScannerTask.java like this
> 
> ```
> private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {
>     HashMap<FileType, List<Document>> documentMap = new HashMap<>();
> 
>     for (final FileType fileType : fileTypes) {
>       ArrayList<Document> documentListFilteredByType = new ArrayList<>();
>       for (Document doc: documents) {
>         if (doc.isThisType(fileType.extensions)) {
>           documentListFilteredByType.add(doc);
>         }
>       }
>       if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
>       documentMap.put(fileType, documentListFilteredByType);
>     }
> 
>     return documentMap;
>   }
> ```

Sorry man! I was a little bit busy! I could not reply beofre. I will try it!

**Comment by datMaster** [comment]
Yes, need to make fork. Also, you should use support library version 28.0.0

**Comment by crismaver1993** [comment]
> Change compileSdkVersion to version 28 and then override method createDocumentType of DocScannerTask.java like this
> 
> ```
> private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {
>     HashMap<FileType, List<Document>> documentMap = new HashMap<>();
> 
>     for (final FileType fileType : fileTypes) {
>       ArrayList<Document> documentListFilteredByType = new ArrayList<>();
>       for (Document doc: documents) {
>         if (doc.isThisType(fileType.extensions)) {
>           documentListFilteredByType.add(doc);
>         }
>       }
>       if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
>       documentMap.put(fileType, documentListFilteredByType);
>     }
> 
>     return documentMap;
>   }
> ```

Did you add something else? I put your code it is ok! But I having issues with Predicate<T> I already imported it but it doesn know .apply  function inside of FilePickerUtils

`public static <T> Collection<T> filter(Collection<T> target, Predicate<T> predicate) {
        Collection<T> result = new ArrayList<T>();
        for (T element : target) {
            if (predicate**.apply**(element)) {
                result.add(element);
            }
        }
        return result;
    }`

**Comment by datMaster** [comment]
> > Change compileSdkVersion to version 28 and then override method createDocumentType of DocScannerTask.java like this
> > ```
> > private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {
> >     HashMap<FileType, List<Document>> documentMap = new HashMap<>();
> > 
> >     for (final FileType fileType : fileTypes) {
> >       ArrayList<Document> documentListFilteredByType = new ArrayList<>();
> >       for (Document doc: documents) {
> >         if (doc.isThisType(fileType.extensions)) {
> >           documentListFilteredByType.add(doc);
> >         }
> >       }
> >       if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
> >       documentMap.put(fileType, documentListFilteredByType);
> >     }
> > 
> >     return documentMap;
> >   }
> > ```
> 
> Did you add something else? I put your code it is ok! But I having issues with Predicate I already imported it but it doesn know .apply function inside of FilePickerUtils
> 
> ```
> `public static <T> Collection<T> filter(Collection<T> target, Predicate<T> predicate) {
>         Collection<T> result = new ArrayList<T>();
>         for (T element : target) {
>             if (predicate**.apply**(element)) {
>                 result.add(element);
>             }
>         }
>         return result;
>     }`
> ```

You can comment this method or delete it.

**Comment by DroidNinja** [comment]
try out new version `2.2.0` with androidx

**Comment by KhanStan99** [comment]
@DroidNinja I have migrated my project to androidx and updated dependancy to 2.2.0

I had to change my code of file picker from:
`FilePickerBuilder.getInstance().setMaxCount(1)
                .setSelectedFiles(filePaths)
                .setActivityTheme(R.style.LibAppTheme)
                .pickPhoto(this);`

to:
 `FilePickerBuilder.Companion.getInstance().setMaxCount(1)
                .setSelectedFiles(filePaths)
                .setActivityTheme(R.style.LibAppTheme)
                .pickPhoto(this);`

Now when i tested the app after setting max compileSdkVersion to 28 i get this error:
  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at droidninja.filepicker.FilePickerBuilder.setSelectedFiles(Unknown Source:2)

**Comment by malcohmx** [comment]
> @DroidNinja I have migrated my project to androidx and updated dependency to 2.2.0
> 
> I had to change my code of file picker from:
> `FilePickerBuilder.getInstance().setMaxCount(1) .setSelectedFiles(filePaths) .setActivityTheme(R.style.LibAppTheme) .pickPhoto(this);`
> 
> to:
> `FilePickerBuilder.Companion.getInstance().setMaxCount(1) .setSelectedFiles(filePaths) .setActivityTheme(R.style.LibAppTheme) .pickPhoto(this);`
> 
> Now when i tested the app after setting max compileSdkVersion to 28 i get this error:
> java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
> at droidninja.filepicker.FilePickerBuilder.setSelectedFiles(Unknown Source:2)

Add this to your app level build.gradle

implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.41'

**Comment by KhanStan99** [comment]
> > @DroidNinja I have migrated my project to androidx and updated dependency to 2.2.0
> > I had to change my code of file picker from:
> > `FilePickerBuilder.getInstance().setMaxCount(1) .setSelectedFiles(filePaths) .setActivityTheme(R.style.LibAppTheme) .pickPhoto(this);`
> > to:
> > `FilePickerBuilder.Companion.getInstance().setMaxCount(1) .setSelectedFiles(filePaths) .setActivityTheme(R.style.LibAppTheme) .pickPhoto(this);`
> > Now when i tested the app after setting max compileSdkVersion to 28 i get this error:
> > java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
> > at droidninja.filepicker.FilePickerBuilder.setSelectedFiles(Unknown Source:2)
> 
> Add this to your app level build.gradle
> 
> implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.41'

Thanks, that error is gone. But here is the new error I'm getting while picking file:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scoratech.scoraxchange.devbuild/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2857)`

**Comment by alexeymorozua** [comment]
> But here is the new error I'm getting while picking file:

I also have this error

**Comment by malcohmx** [comment]
> > But here is the new error I'm getting while picking file:
> 
> I also have this error

check my previous replies.

Here is the solution
I've resolved the issue by adding .sortDocumentsBy(SortingTypes.name) to the builder method.

**Comment by dishantghai** [comment]
I solved this by :- 
(1.)  Adding following to App Level build.gradle ->

```
dependency{
 ...
 implementation 'com.droidninja:filepicker:2.2.0'
 implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71"
...
}

configurations {
    cleanedAnnotations
    compile.exclude group: 'org.jetbrains' , module:'annotations'
}
```

(2) Changing ->
```
FilePickerBuilder.getInstance().setMaxCount(1)
                                .setSelectedFiles(file_paths)
                                .setActivityTheme(R.style.FilePickerTheme)
                                .pickPhoto(this);
```
                             
                 --- TO ---

```
FilePickerBuilder.Companion.getInstance().setMaxCount(1)
                                .setSelectedFiles(file_paths)
                                .setActivityTheme(R.style.FilePickerTheme)
                                .sortDocumentsBy(SortingTypes.name)
                                .pickPhoto(this);
```

**Comment by KhanStan99** [comment]
> I solved this by :-
> (1.) Adding following to App Level build.gradle ->
> 
> ```
> dependency{
>  ...
>  implementation 'com.droidninja:filepicker:2.2.0'
>  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71"
> ...
> }
> 
> configurations {
>     cleanedAnnotations
>     compile.exclude group: 'org.jetbrains' , module:'annotations'
> }
> ```
> (2) Changing ->
> 
> ```
> FilePickerBuilder.getInstance().setMaxCount(1)
>                                 .setSelectedFiles(file_paths)
>                                 .setActivityTheme(R.style.FilePickerTheme)
>                                 .pickPhoto(this);
> ```
> ```
>              --- TO ---
> ```
> ```
> FilePickerBuilder.Companion.getInstance().setMaxCount(1)
>                                 .setSelectedFiles(file_paths)
>                                 .setActivityTheme(R.style.FilePickerTheme)
>                                 .sortDocumentsBy(SortingTypes.name)
>                                 .pickPhoto(this);
> ```

You moved your project your AndroidX?and tested both file and photo picker?

**Comment by KhanStan99** [comment]
I tried @dishantghai changes.

Getting this error: 
`error: cannot access Fragment
class file for androidx.fragment.app.Fragment not found`

**Comment by mohammadidiab** [comment]
download last comment before converted to kotlin from this link :
[https://github.com/DroidNinja/Android-FilePicker/tree/95216ceeeac3ea95939f6fcf0d1d18ea320d4829](url)
then you can update the
compileSdkVersion 28
targetSdkVersion 26

then add 
implementation project(path: ':filepicker', configuration: 'default')

then go to DocScannerTask 
replace 

`private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {   HashMap<FileType, List<Document>> documentMap = new HashMap<>();
    for (final FileType fileType : fileTypes) {
      Predicate<Document> docContainsTypeExtension = new Predicate<Document>() {
        public boolean apply(Document document) {
          return document.isThisType(fileType.extensions);
        }
      };
      ArrayList<Document> documentListFilteredByType =
          (ArrayList<Document>) FilePickerUtils.filter(documents, docContainsTypeExtension);
      if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
      documentMap.put(fileType, documentListFilteredByType);
    }
    return documentMap;
  } 
`

To

` private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {HashMap<FileType, List<Document>> documentMap = new HashMap<>();
    for (final FileType fileType : fileTypes) {
      ArrayList<Document> documentListFilteredByType = new ArrayList<>();
      for (Document doc: documents) {
        if (doc.isThisType(fileType.extensions)) {
          documentListFilteredByType.add(doc);
        }
      }
      if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
      documentMap.put(fileType, documentListFilteredByType);
    }
    return documentMap;
  }`

then Go to FilePickerUtils And remove 
`public static <T> Collection<T> filter(Collection<T> target, Predicate<T> predicate) {
        Collection<T> result = new ArrayList<T>();
        for (T element : target) {
            if (predicate**.apply**(element)) {
                result.add(element);
            }
        }
        return result;
    }`

**Comment by him2016** [comment]
> tried @dishantghai changes.
> 
> Getting this error:
> `error: cannot access Fragment class file for androidx.fragment.app.Fragment not found`

Any solution to this issue yet..?

**Comment by KhanStan99** [comment]
@DroidNinja Please help us out. Can we use your library on latest SDK without migrating to androidx ?

**Comment by LaoXiZi** [comment]
I have the same issue.

**Comment by LaoXiZi** [comment]
I can't find hope to fix the bug as soon as possible

**Comment by astend** [comment]
have this issue too

**Comment by nguyencongbinh** [comment]
Please help to fix this issues. :(

**Comment by asdec** [comment]
> Change compileSdkVersion to version 28 and then override method createDocumentType of DocScannerTask.java like this
> 
> ```
> private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {
>     HashMap<FileType, List<Document>> documentMap = new HashMap<>();
> 
>     for (final FileType fileType : fileTypes) {
>       ArrayList<Document> documentListFilteredByType = new ArrayList<>();
>       for (Document doc: documents) {
>         if (doc.isThisType(fileType.extensions)) {
>           documentListFilteredByType.add(doc);
>         }
>       }
>       if (comparator != null) Collections.sort(documentListFilteredByType, comparator);
>       documentMap.put(fileType, documentListFilteredByType);
>     }
> 
>     return documentMap;
>   }
> ```

How to do that with the gradle dependancy 2.2.0?

**Comment by zero-li** [comment]
> download last comment before converted to kotlin from this link :
> [https://github.com/DroidNinja/Android-FilePicker/tree/95216ceeeac3ea95939f6fcf0d1d18ea320d4829](url)
> then you can update the
> compileSdkVersion 28
> targetSdkVersion 26
> 
> then add
> implementation project(path: ':filepicker', configuration: 'default')
> 
> then go to DocScannerTask
> replace
> 
> `private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) { HashMap<FileType, List<Document>> documentMap = new HashMap<>(); for (final FileType fileType : fileTypes) { Predicate<Document> docContainsTypeExtension = new Predicate<Document>() { public boolean apply(Document document) { return document.isThisType(fileType.extensions); } }; ArrayList<Document> documentListFilteredByType = (ArrayList<Document>) FilePickerUtils.filter(documents, docContainsTypeExtension); if (comparator != null) Collections.sort(documentListFilteredByType, comparator); documentMap.put(fileType, documentListFilteredByType); } return documentMap; } `
> 
> To
> 
> ` private HashMap<FileType, List<Document>> createDocumentType(ArrayList<Document> documents) {HashMap<FileType, List<Document>> documentMap = new HashMap<>(); for (final FileType fileType : fileTypes) { ArrayList<Document> documentListFilteredByType = new ArrayList<>(); for (Document doc: documents) { if (doc.isThisType(fileType.extensions)) { documentListFilteredByType.add(doc); } } if (comparator != null) Collections.sort(documentListFilteredByType, comparator); documentMap.put(fileType, documentListFilteredByType); } return documentMap; }`
> 
> then Go to FilePickerUtils And remove
> `public static <T> Collection<T> filter(Collection<T> target, Predicate<T> predicate) { Collection<T> result = new ArrayList<T>(); for (T element : target) { if (predicate**.apply**(element)) { result.add(element); } } return result; }`
> 
> @KhanStan99

fix this isuue 
```
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName version
    }

    implementation 'com.github.bumptech.glide:glide:4.8.0'

```
[filepicker-2.1.5-20190416-aar.zip](https://github.com/DroidNinja/Android-FilePicker/files/3082748/filepicker-2.1.5-20190416-aar.zip)
