### ISSUE TITLE
PickerManager.sortingType.comparator must not be null

### ISSUE THREAD

**Issue by Virendra-Varma** [DroidNinja/Android-FilePicker#205]
`java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null
        at droidninja.filepicker.fragments.DocPickerFragment.setData(DocPickerFragment.kt:82)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.kt:66)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.kt:61)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:896)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2609)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2565)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:245)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:525)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:179)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1356)
        at android.app.Activity.performStart(Activity.java:7052)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
`
unable to open the filePicker here is my code
`
        FilePickerBuilder.Companion.getInstance()
            .setActivityTitle(getString(R.string.selectTheKmlFile))
            .enableCameraSupport(false)
            .enableDocSupport(true)
            .enableImagePicker(false)
            .enableSelectAll(false)
            .enableVideoPicker(false)
            .showFolderView(true)
            .setSelectedFiles(kmlFileList)
            .addFileSupport(getString(R.string.selectTheKmlFile), new String[] { "kml" })
            .setMaxCount(1)
            .pickFile(this, REQUEST_CODE);`

**Comment by HeshamMorsy** [comment]
I had this issue but it was fixed when I added this line :
                .sortDocumentsBy(SortingTypes.name)

my file picker is written as following code :

FilePickerBuilder.Companion.getInstance()
                .setMaxCount(1)
                .setSelectedFiles(new ArrayList<>())
                .setActivityTheme(R.style.LibAppTheme)
                .showFolderView(true)
                .sortDocumentsBy(SortingTypes.name)
                .pickFile(ChatActivity.this, REQUEST_CODE_DOC);
