### ISSUE TITLE
ava.lang.ClassNotFoundException: Didn't find class "droidninja.filepicker.utils.FilePickerProvider"

### ISSUE THREAD

**Issue by ghazzan** [DroidNinja/Android-FilePicker#209]
when i update library into newest, i got this error
`01-22 17:54:03.588 7992-7992/com.git.mami.kos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.git.mami.kos, PID: 7992
    java.lang.RuntimeException: Unable to get provider droidninja.filepicker.utils.FilePickerProvider: java.lang.ClassNotFoundException: Didn't find class "droidninja.filepicker.utils.FilePickerProvider" on path: DexPathList[[zip file "/data/app/com.git.mami.kos-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5383)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4975)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4915)
        at android.app.ActivityThread.access$1600(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5753)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "droidninja.filepicker.utils.FilePickerProvider" on path: DexPathList[[zip file "/data/app/com.git.mami.kos-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5368)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4975) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4915) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:168) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
    	Suppressed: java.lang.NoClassDefFoundError: droidninja.filepicker.utils.FilePickerProvider
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:321)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 14 more
    	Suppressed: java.lang.ClassNotFoundException: droidninja.filepicker.utils.FilePickerProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Comment by dn0myaraymond** [comment]
same issue :(
