### ISSUE TITLE
kotlin.TypeCastException: null cannot be cast to non-null type droidninja.filepicker.fragments.DocFragment

### ISSUE THREAD

**Issue by jipspaul** [DroidNinja/Android-FilePicker#210]
This only happen on Samsung mobile running android 8.

Fatal Exception: kotlin.TypeCastException: null cannot be cast to non-null type droidninja.filepicker.fragments.DocFragment
       at droidninja.filepicker.fragments.DocPickerFragment.setDataOnFragments(DocPickerFragment.kt:99)
       at droidninja.filepicker.fragments.DocPickerFragment.access$setDataOnFragments(DocPickerFragment.kt:23)
       at droidninja.filepicker.fragments.DocPickerFragment$setData$$inlined$let$lambda$1.onResultCallback(DocPickerFragment.kt:86)
       at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.kt:72)
       at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.kt:29)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(Unknown Source)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by fereshteh-jvz** [comment]
This happened on android emulator 7 too.
