### ISSUE TITLE
Bug in ReadMe sample implementation code

### ISSUE THREAD

**Issue by JobGetabu** [DroidNinja/Android-FilePicker#214]
02-26 12:07:59.470 16058-16058/ke.co.presta.lender E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ke.co.presta.lender, PID: 16058
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ke.co.presta.lender/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null
        at droidninja.filepicker.fragments.DocPickerFragment.setData(DocPickerFragment.kt:82)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.kt:66)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.kt:61)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:896)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2609)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2565)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:245)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:525)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:179)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
        at android.app.Activity.performStart(Activity.java:6116)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by DroidNinja** [comment]
Try 2.2.3. Reopen if still happening
