### ISSUE TITLE
Cannot use Library with MDC(Material design) theme in android

### ISSUE THREAD

**Issue by JobGetabu** [DroidNinja/Android-FilePicker#215]
02-26 12:14:48.072 17091-17091/ke.co.presta.lender E/MessageQueue-JNI: java.lang.IncompatibleClassChangeError: Class 'droidninja.filepicker.utils.TabLayoutHelper$2' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:801)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1763)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1747)
        at com.google.android.material.tabs.TabLayout$TabLayoutOnPageChangeListener.onPageSelected(TabLayout.java:2994)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2263)
        at android.view.View.dispatchTouchEvent(View.java:8593)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2513)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2157)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2482)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1798)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2797)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2443)
        at android.view.View.dispatchPointerEvent(View.java:8799)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4662)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4520)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4190)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4247)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
    	at android.view.Vie

**Comment by JobGetabu** [comment]
Fixed by
` implementation 'com.google.android.material:material:1.0.0'`

**Comment by rahul860366** [comment]
> Fixed by
> ` implementation 'com.google.android.material:material:1.0.0'`

Not working. Still crashing

**Comment by muthu1001** [comment]
Its crashing

**Comment by SimoStack** [comment]
I have the same problem, solved downgrading droidninja version.
On working project i've:
```
implementation 'com.google.android.material:material:1.2.0-alpha01'
implementation 'com.droidninja:filepicker:2.1.5'
```
