### ISSUE TITLE
When you press back key when its loading...

### ISSUE THREAD

**Issue by JobGetabu** [DroidNinja/Android-FilePicker#216]
02-26 12:54:08.760 21725-21725/.../, PID: 21725
    java.lang.IllegalStateException: Fragment has not been attached yet.
        at androidx.fragment.app.Fragment.instantiateChildFragmentManager(Fragment.java:2383)
        at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:845)
        at droidninja.filepicker.fragments.DocPickerFragment.setDataOnFragments(DocPickerFragment.kt:98)
        at droidninja.filepicker.fragments.DocPickerFragment.access$setDataOnFragments(DocPickerFragment.kt:23)
        at droidninja.filepicker.fragments.DocPickerFragment$setData$$inlined$let$lambda$1.onResultCallback(DocPickerFragment.kt:86)
        at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.kt:72)
        at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.kt:29)
        at android.os.AsyncTask.finish(AsyncTask.java:636)
        at android.os.AsyncTask.access$500(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by DroidNinja** [comment]
Try 2.2.3. Reopen if still happening
