### ISSUE TITLE
Glide 4.9.0 conflict on photoPicker

### ISSUE THREAD

**Issue by jomarierafa** [DroidNinja/Android-FilePicker#220]
java.lang.NoSuchMethodError: No virtual method override(II)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.oa.v2.dev-2/split_lib_dependencies_apk.apk)
        at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:74)
        at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:24)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15697)
        at android.view.ViewGroup.layout(ViewGroup.java:5064)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15697)

**Comment by jomarierafa** [comment]
v2.1.5

**Comment by DroidNinja** [comment]
This is known issue. Fixing it in next release

**Comment by ashishgupta-kiwi** [comment]
Same issue i found with glide conflict . please fix

**Comment by qq2956218657** [comment]
Same issue

**Comment by nathansdev** [comment]
is this issue fixed ?. I am facing the same problem in 2.1.5. Glide version I am using is 4.9.0.

**Comment by RabieMohimane** [comment]
> is this issue fixed ?. I am facing the same problem in 2.1.5. Glide version I am using is 4.9.0. @DroidNinja

same issue

**Comment by DroidNinja** [comment]
Fixed this issue in the last release. Not providing support for without androidx codebases. Try updating your code and use latest version.
