### ISSUE TITLE
Error when clicking tab in file picker

### ISSUE THREAD

**Issue by hendrawd** [DroidNinja/Android-FilePicker#225]
I'm already using androidx

Library used in gradle file
```groovy
    implementation 'com.droidninja:filepicker:2.2.1'
```

Code for opening file picker
```kotlin
FilePickerBuilder.instance.setMaxCount(1)
    .setActivityTheme(R.style.LibAppTheme)
    .pickFile(this)
```

The code above will open an Activity for picking file with tabs. When I click the second tab, application will force closed.

Stacktrace
```
java.lang.IncompatibleClassChangeError: Class 'droidninja.filepicker.utils.TabLayoutHelper$2' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/my.app.package-1/split_lib_dependencies_apk.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:824)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1796)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1780)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1743)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2089)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2274)
        at android.view.View$PerformClick.run(View.java:23239)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1064)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```

**Comment by hendrawd** [comment]
After I changed the version to 
```groovy
implementation 'com.droidninja:filepicker:2.1.5'
```
And click the second tab, it working fine.

**Comment by yamifr07** [comment]
Same isuse

**Comment by sranjith096** [comment]
This will work if we use the stable version of material components library
`implementation 'com.google.android.material:material:1.0.0'`

Future versions use `BaseOnTabSelectedListener`. 

Check the updated doc:
[https://developer.android.com/reference/com/google/android/material/tabs/package-summary](url)

Hopefully, Google should release a stable version with updated stuff soon. It's since 7 months we've received a beta/stable release in material components library.

**Comment by hendrawd** [comment]
@sranjith096 Hmm I see. Thank you for investigating this. I might implement your solution in the future.

**Comment by DroidNinja** [comment]
This will work if you use update your dependencies.
Closing it as @sranjith096 provided the [solution](https://github.com/DroidNinja/Android-FilePicker/issues/225#issuecomment-506214892).

**Comment by akeditzz** [comment]
After using @sranjith096 's also same result, going back to old verison worked for me

**Comment by johnernest02** [comment]
> This will work if you use update your dependencies.
> Closing it as @sranjith096 provided the [solution](https://github.com/DroidNinja/Android-FilePicker/issues/225#issuecomment-506214892).

I have updated dependencies but still crashes. I'm restricting only one file type for file pickers now because of this. I hope it will be fixed soon
