### ISSUE TITLE
I try to pick up document file like pdf,txt,etc but it crash

### ISSUE THREAD

**Issue by Geet2312** [DroidNinja/Android-FilePicker#228]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.skoolsync.app, PID: 12765
    java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Lcom/google/android/material/tabs/TabLayout$OnTabSelectedListener;)V in class Lcom/google/android/material/tabs/TabLayout; or its super classes (declaration of 'com.google.android.material.tabs.TabLayout' appears in /data/app/com.skoolsync.app-cjOWgjwIOQ_oIpFv3pMj2Q==/base.apk)
        at droidninja.filepicker.utils.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:351)
        at droidninja.filepicker.utils.TabLayoutHelper.<init>(TabLayoutHelper.java:100)
        at droidninja.filepicker.fragments.DocPickerFragment.setUpViewPager(DocPickerFragment.java:145)
        at droidninja.filepicker.fragments.DocPickerFragment.initView(DocPickerFragment.java:85)
        at droidninja.filepicker.fragments.DocPickerFragment.onViewCreated(DocPickerFragment.java:81)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7397)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3199)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:185)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:170)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:147)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7183)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by DroidNinja** [comment]
Try to update your codebase with androidx. These issues are generally due to conflicting support libraries.
Check this: https://stackoverflow.com/questions/52926241/tab-layout-nosuchmethoderror-on-addontabselectedlistener

**Comment by tusharuit25** [comment]
I have followed all instructions given at https://stackoverflow.com/questions/52926241/tab-layout-nosuchmethoderror-on-addontabselectedlistener but still same issue persist below is my gradle

`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.29.0'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
//apply plugin: 'android-apt'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 28
    //buildToolsVersion "27.0.1"
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.xxx.xxx"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 15
        versionName "2.0.2"
        renderscriptTargetApi 28 //must match target sdk and build tools
        renderscriptSupportModeEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        //manifestPlaceholders = [HOCKEYAPP_APP_ID: "249af83877924b1e8ede4296a5d6a8ea"]
        resConfigs "en"
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"  // app size reduction option
        }

    }
    dexOptions {
        preDexLibraries true
        javaMaxHeapSize "6g"
        //incremental true
        dexInProcess = true
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {

            debuggable false
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            jniDebuggable false
            renderscriptDebuggable false
            pseudoLocalesEnabled false
            zipAlignEnabled true


        }
    }

    configurations.all {
        resolutionStrategy {
            force 'com.android.support:exifinterface:28.0.0'
            force 'com.android.support:mediarouter-v7:28.0.0'
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
        // exclude 'META-INF/ASL2.0'
    }
    dataBinding {
        enabled = true
    }
    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
        maven {
            url 'http://dl.bintray.com/amulyakhare/maven'
        }
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://github.com/leonardocardoso/mvn-repo/raw/master/maven-deploy' }
    }

}

dependencies {

    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
}

apply plugin: 'com.google.gms.google-services'


`
