### ISSUE TITLE
TablayoutHelper does not implement interface

### ISSUE THREAD

**Issue by JhomariAsinas** [DroidNinja/Android-FilePicker#232]
im using 2.2.1 and i got this error

`Stack trace:  
java.lang.IncompatibleClassChangeError: Class 'droidninja.filepicker.utils.TabLayoutHelper$2' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.oa.v2.dev-bS3Pe54IHU5c9X6zMHkCTg==/base.apk!classes2.dex)
 at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:801)
 at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1762)
 at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1746)
 at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1709)
 at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2054)
 at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2239)
 at android.view.View$PerformClick.run(View.java:24993)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:192)
 at android.app.ActivityThread.main(ActivityThread.java:6710)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)`

Is there any suggestion or way to fix this?. i already migrated my app to androidX

**Comment by sivabe35** [comment]
Need update in TabLayoutHelper class.
The fix is to use TabLayout.BaseOnTabSelectedListener instead of  TabLayout.OnTabSelectedListener.

**Comment by Rajnish23** [comment]
How can I update my code? @sivabe35

**Comment by sivabe35** [comment]
https://stackoverflow.com/questions/32600325/android-studio-add-library-from-github @Rajnish23
