### ISSUE TITLE
Wrong table field when u looks for images

### ISSUE THREAD

**Issue by dav93ide** [DroidNinja/Android-FilePicker#234]
java.lang.IllegalArgumentException: column 'bucket_id' does not exist. Available columns: [instance_id, format, height, is_drm, owner_package_name, parent, date_modified, date_expires, _display_name, mime_type, _id, _data, _hash, _size, title, width, is_trashed, document_id, is_download, is_pending, date_added, primary_directory, secondary_directory, original_document_id, media_type, relative_path]

**Comment by dav93ide** [comment]
Still have the same problem...
Can you solve please or I need to implement alone the photo picker? :/ (= waste of time for me lol)

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.ubikinformatica.it.eteam, PID: 7040
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: column 'bucket_id' does not exist. Available columns: [instance_id, format, height, is_drm, owner_package_name, parent, date_modified, date_expires, _display_name, mime_type, _id, _data, _hash, _size, title, width, is_trashed, document_id, is_download, is_pending, date_added, primary_directory, secondary_directory, original_document_id, media_type, relative_path]
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
        at droidninja.filepicker.cursors.PhotoScannerTask.getPhotoDirectories(PhotoScannerTask.kt:79)
        at droidninja.filepicker.cursors.PhotoScannerTask.doInBackground(PhotoScannerTask.kt:58)
        at droidninja.filepicker.cursors.PhotoScannerTask.doInBackground(PhotoScannerTask.kt:33)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
E/RecyclerView: No adapter attached; skipping layout

**Comment by dav93ide** [comment]
Anyway I found version "1.0.8" works with androidx and doesn't have this problem, thx

**Comment by DroidNinja** [comment]
Try 2.2.2.
