### ISSUE TITLE
Crash when tap on "All photos" 

### ISSUE THREAD

**Issue by nguyencongbinh** [DroidNinja/Android-FilePicker#260]
My device (Samsung A9, Android 9) got crash when pick photo then tap on "All Photos" item. 
It works when tap on "Screenshots",  "Camera".

`2020-04-12 08:21:19.881 1745-7175/? E/Parcel: Class not found when unmarshalling: droidninja.filepicker.models.PhotoDirectory
    java.lang.ClassNotFoundException: droidninja.filepicker.models.PhotoDirectory
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2827)
        at android.os.Parcel.readParcelable(Parcel.java:2781)
        at android.os.Parcel.readValue(Parcel.java:2684)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getString(BaseBundle.java:1155)
        at android.content.Intent.getStringExtra(Intent.java:8114)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:727)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:665)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1542)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:606)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6693)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6584)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6575)
        at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10845)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:111)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4162)
        at android.os.Binder.execTransact(Binder.java:739)`

**Comment by sagarzala123** [comment]
I faced same issue.

**Comment by DroidNinja** [comment]
Fixed in 2.2.4. Please check
