### ISSUE TITLE
Is Kotlin required to integrate this SDK? I am getting following error. Lkotlinx/coroutines/Dispatchers

### ISSUE THREAD

**Issue by adityapise** [DroidNinja/Android-FilePicker#274]
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15)
        at droidninja.filepicker.fragments.MediaPickerFragment.<init>(MediaPickerFragment.kt:16)
        at droidninja.filepicker.fragments.MediaPickerFragment$Companion.newInstance(MediaPickerFragment.kt:83)
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:74)
        at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.kt:48)
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.kt:26)
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" on path: DexPathList[[zip file "/data/app/com.-sAmhJJsLc15__eyhZyd4Pg==/base.apk"],nativeLibraryDirectories=[/data/app/com.-sAmhJJsLc15__eyhZyd4Pg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by adityapise** [comment]
Added following lib as well Still same issue
1. implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
2. classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
3. implementation 'androidx.appcompat:appcompat:1.1.0'
Plugin:
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

Extra Info:
minSdkVersion 23
targetSdkVersion 29

**Comment by architpuri** [comment]
Getting the same issue using Java 
minSdkVersion 24
targetSdkVersion 28
'gradle:3.6.1'

   `    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15)
        at droidninja.filepicker.fragments.DocPickerFragment.<init>(DocPickerFragment.kt:21)
        at droidninja.filepicker.fragments.DocPickerFragment$Companion.newInstance(DocPickerFragment.kt:119)
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:79)
        at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.kt:48)
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.kt:26)
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Activity.performCreate(Activity.java:7131)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" on path: DexPathList[[zip file "/data/app/in.themoneytree-_qflKKkch4tBbJkEcL3_5w==/base.apk"],nativeLibraryDirectories=[/data/app/in.themoneytree-_qflKKkch4tBbJkEcL3_5w==/lib/arm64, /data/app/in.themoneytree-_qflKKkch4tBbJkEcL3_5w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15) 
        at droidninja.filepicker.fragments.DocPickerFragment.<init>(DocPickerFragment.kt:21) 
        at droidninja.filepicker.fragments.DocPickerFragment$Companion.newInstance(DocPickerFragment.kt:119) 
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:79) 
        at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.kt:48) 
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.kt:26) 
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:24) 
        at android.app.Activity.performCreate(Activity.java:7140) 
        at android.app.Activity.performCreate(Activity.java:7131) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by ravithoria** [comment]
same issue using Java

**Comment by adityapise** [comment]
Resolved by adding SDK as "Gradle Project" and then adding following lines in build.gradle.
Project level:
        ext.kotlin_version = '1.3.72'

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
App level:
implementation project(path: ':filepicker')

Please check error you are getting while build and add dependencies accordingly.

**Comment by bujinhai** [comment]
I also have this question, Do you solve it? by the way, i use kotlin

**Comment by bujinhai** [comment]
> Added following lib as well Still same issue
> 
> 1. implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
> 2. classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
> 3. implementation 'androidx.appcompat:appcompat:1.1.0'
>    Plugin:
>    apply plugin: 'kotlin-android'
>    apply plugin: 'kotlin-android-extensions'
> 
> Extra Info:
> minSdkVersion 23
> targetSdkVersion 29

 I'm in your configuration, but it does n' t work, i also use kotlin

**Comment by adityapise** [comment]
> 
> 
> > Added following lib as well Still same issue
> > 
> > 1. implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
> > 2. classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
> > 3. implementation 'androidx.appcompat:appcompat:1.1.0'
> >    Plugin:
> >    apply plugin: 'kotlin-android'
> >    apply plugin: 'kotlin-android-extensions'
> > 
> > Extra Info:
> > minSdkVersion 23
> > targetSdkVersion 29
> 
> I'm in your configuration, but it does n' t work, i also use kotlin

Kindly share error you are getting

**Comment by chaitu14** [comment]
I'm also getting same issue 
Please check attached screenshots of configuration and logcat errors

<img width="62
<img width="1373" alt="Screenshot 2020-07-06 at 2 01 47 PM" src="https://user-images.githubusercontent.com/4597742/86573114-89209b00-bf91-11ea-976b-ac45ed2cabe1.png">
7" alt="Screenshot 2020-07-06 at 2 00 52 PM" src="https://user-images.githubusercontent.com/4597742/86573107-8756d780-bf91-11ea-911e-ee19f6cdbdbd.png">
<img width="777" alt="Screenshot 2020-07-06 at 2 01 00 PM" src="https://user-images.githubusercontent.com/4597742/86573110-88880480-bf91-11ea-9365-b98af954bc5f.png">

**Comment by adityapise** [comment]
I can help but my solution works for me but not for all. Please check my above Answer

**Comment by chaitu14** [comment]
Thankyou for your reply,I follow the same added all kotlin related stuff. still I'm unable find why its not working.

**Comment by suleiman-azhari** [comment]
Resolved by adding Coroutines dependencies to app build.gradle
    
```
dependencies {

...

implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.8"
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.8'

}
```
