### ISSUE TITLE
Unable to find explicit activity class

### ISSUE THREAD

**Issue by sshiyani** [DroidNinja/Android-FilePicker#279]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.app.docterz/droidninja.filepicker.FilePickerActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1952)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1624)
        at android.app.Activity.startActivityForResult(Activity.java:4621)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
        at droidninja.filepicker.FilePickerBuilder.start(FilePickerBuilder.kt:180)
        at droidninja.filepicker.FilePickerBuilder.pickPhoto(FilePickerBuilder.kt:112)

anyone can help?

**Comment by DroidNinja** [comment]
How did you integrated this library? Need some details for this.

**Comment by sshiyani** [comment]
@DroidNinja problem solved by declaring required activities in manifest. i thought its library so do not required to add in manifest file. thank you for followup my issue
