### ISSUE TITLE
Crashing in Android 10

### ISSUE THREAD

**Issue by jimmytrivedi** [DroidNinja/Android-FilePicker#280]
While opening Document picker:

 ```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15)
        at droidninja.filepicker.fragments.DocPickerFragment.<init>(DocPickerFragment.kt:21)
        at droidninja.filepicker.fragments.DocPickerFragment$Companion.newInstance(DocPickerFragment.kt:119)
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:79)
```

**Comment by KiwanPark** [comment]
implimentation this for build.graddle app

    //coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.4"

it works for me :)

**Comment by jimmytrivedi** [comment]
No for Java, it is not working
