### ISSUE TITLE
Camera Crashing on click a pic and done  

### ISSUE THREAD

**Issue by rishipaulcodebrewinnovations** [DroidNinja/Android-FilePicker#304]
Camera is crashing on click a pic and then on done its getting crashed, And minimising the app. please suggest.

**Comment by DroidNinja** [comment]
Please post crash logs

**Comment by user9846cbl** [comment]
Its crashing in targetSdkVersion 30. Please recommend any solution

**Comment by DroidNinja** [comment]
Need crash logs for debugging

**Comment by user9846cbl** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.physiotherapist.vendor/com.consultantvendor.ui.dashboard.HomeActivity}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException
	at androidx.lifecycle.LifecycleRegistry.downEvent(LifecycleRegistry.java:263)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:314)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:118)
	at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.java:150)
	at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.java:130)
	at androidx.navigation.NavController.popBackStackInternal(NavController.java:325)
	at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.java:426)
	at androidx.navigation.NavController.onGraphCreated(NavController.java:636)
	at androidx.navigation.NavController.setGraph(NavController.java:586)
	at androidx.navigation.NavController.setGraph(NavController.java:551)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:247)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:44)
	at com.consultantvendor.ui.dashboard.HomeActivity.onCreate(HomeActivity.kt:38)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
	... 11 more

**Comment by user9846cbl** [comment]
Also take a pick, cross and save button comes, go back from here, without clicking on any button, it crashes

**Comment by user9846cbl** [comment]
Please Check this video, May be it will clarify you 
https://user-images.githubusercontent.com/74241015/104693564-e3b06600-572f-11eb-8689-d3677ae9361f.mp4
