### ISSUE TITLE
Crash Coroutines

### ISSUE THREAD

**Issue by harcoPro** [DroidNinja/Android-FilePicker#308]
2020-11-23 12:40:30.059 14514-14514/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.vtb.smb.debugK3, PID: 14514
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15)
        at droidninja.filepicker.fragments.MediaPickerFragment.<init>(MediaPickerFragment.kt:16)
        at droidninja.filepicker.fragments.MediaPickerFragment$Companion.newInstance(MediaPickerFragment.kt:83)
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:74)
        at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.kt:48)
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.kt:26)
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" on path: DexPathList[[zip file "/data/app/~~1bG2TG8VOZo2uAAcKuQAGQ==/ru.vtb.smb.debugK3-H7Ot6hs4L9un-UNCn7FClw==/base.apk"],nativeLibraryDirectories=[/data/app/~~1bG2TG8VOZo2uAAcKuQAGQ==/ru.vtb.smb.debugK3-H7Ot6hs4L9un-UNCn7FClw==/lib/arm64, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at droidninja.filepicker.fragments.BaseFragment.<init>(BaseFragment.kt:15) 
        at droidninja.filepicker.fragments.MediaPickerFragment.<init>(MediaPickerFragment.kt:16) 
        at droidninja.filepicker.fragments.MediaPickerFragment$Companion.newInstance(MediaPickerFragment.kt:83) 
        at droidninja.filepicker.FilePickerActivity.openSpecificFragment(FilePickerActivity.kt:74) 
        at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.kt:48) 
        at droidninja.filepicker.BaseFilePickerActivity.onCreate(BaseFilePickerActivity.kt:26) 
        at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:24) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656)

**Comment by VikasPawar2112** [comment]
Also i have same issue but i have added the below dependencies and work fine for me.
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9'
