### ISSUE TITLE
Crash RuntimeException: android.os.TransactionTooLargeException: data parcel size 550896 bytes

### ISSUE THREAD

**Issue by mrkayza** [DroidNinja/Android-FilePicker#338]
Hi.
I'm using Samsung Galaxy 8plus, Android 9.
Please help me.
This is logcat (My phone there are a lot of pictures):

`AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 15630
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 550896 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.os.TransactionTooLargeException: data parcel size 550896 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3891)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) `

**Comment by mrkayza** [comment]
I'm using lastest lib version 2.2.5

**Comment by mrkayza** [comment]
@DroidNinja Can you help me ? Please.
