### ISSUE TITLE
Crash If I doesnt add this method .setSelectedFiles()

### ISSUE THREAD

**Issue by thatsmoodi** [DroidNinja/Android-FilePicker#43]
I dont want to set selected Files. If I doesnt add this method The app crashed.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5481)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                          at droidninja.filepicker.PickerManager.add(PickerManager.java:83)
                                                                          at droidninja.filepicker.FilePickerActivity.initView(FilePickerActivity.java:60)
                                                                          at droidninja.filepicker.FilePickerActivity.onCreate(FilePickerActivity.java:45)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5481) 
                                                                          at java.lang.reflect.Method.invoke(Native Method

**Comment by DroidNinja** [comment]
Fixed in 2.0.2. Close If resolved.

**Comment by thatsmoodi** [comment]
Thanks for quick reply and a quick solve :)
