### ISSUE TITLE
When returning fast to previous activity it crashes

### ISSUE THREAD

**Issue by vnavarro** [DroidNinja/Android-FilePicker#55]
Steps to reproduce
1- Open the file picker in Docs mode
2- Before it can finish loading hit back
3- Crash happens

Code used
```
FilePickerBuilder.getInstance().setMaxCount(1)
                    .setSelectedFiles(new ArrayList<String>())
                    .setActivityTheme(R.style.AppTheme)
                    .pickFile(this);
```
Also I open it from a menu option in the action bar, which shouldn't mean much.

Something strange I noticed is that I don't see the action bar in FilePickerActivity when opening from my app but I see it when executing from demo code.

Here's the stack trace
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: br.com.appname, PID: 15775
java.lang.IllegalStateException: Fragment has not been attached yet.
at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2154)
at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:704)
at droidninja.filepicker.fragments.DocPickerFragment.setDataOnFragments(DocPickerFragment.java:95)
at droidninja.filepicker.fragments.DocPickerFragment.access$100(DocPickerFragment.java:31)
at droidninja.filepicker.fragments.DocPickerFragment$1.onResultCallback(DocPickerFragment.java:85)
at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.java:70)
at droidninja.filepicker.cursors.DocScannerTask.onPostExecute(DocScannerTask.java:25)
at android.os.AsyncTask.finish(AsyncTask.java:636)
at android.os.AsyncTask.access$500(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

My suggestion is to cut task execution if filepicker activity is dismissed.

**Comment by vnavarro** [comment]
Couldn't reproduce on demo app, but while debugging and looking for an anwser I found that maybe [isAdded()](https://developer.android.com/reference/android/app/Fragment.html#isAdded()) would be simpler than cutting task execution.

**Comment by DroidNinja** [comment]
fixed in latest build. Please confirm and close bug. Thanks.
