### ISSUE TITLE
Crash when using Glide v4

### ISSUE THREAD

**Issue by nic003** [DroidNinja/Android-FilePicker#83]
```
FATAL EXCEPTION: main
                                                                              Process: apps.synchronytelemed.hubchart, PID: 9471
                                                                              java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/apps.synchronytelemed.hubchart-1/split_lib_dependencies_apk.apk:classes65.dex)
                                                                                  at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:69)
                                                                                  at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:22)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
                                                                                  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1694)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1470)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                                                                                  at android.view.View.layout(View.java:15779)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5069)
                                                                              	at android.widget.FrameLayout.layoutChildren(FrameLay

```

**Comment by dev-JE02** [comment]
I really like this library as it is the easiest to implement among all others I have used. But I believe Glide v4 is a lot more stable than v3. Please migrate to using Glide v4 and implement GlideModule scheme so that it doesn't break on subsequent updates to the Glide library, or atleast there would be a way around it.

**Comment by DroidNinja** [comment]
@nic003 Did you tried clean and rebuild again?

**Comment by DroidNinja** [comment]
updated to glide v4. Hope this problem will fix in 2.0.8.

**Comment by nick-kleban** [comment]
@DroidNinja I have this issue after i updated Glide from 4.0.0-RC1 to 4.0.0
I use 2.0.8 version of library. 
`    compile 'com.droidninja:filepicker:2.0.8'
`

` java.lang.NoSuchFieldError: No field iv_photo of type I in class Ldroidninja/filepicker/R$id; or its superclasses (declaration of 'droidninja.filepicker.R$id' appears in /data/app/se.euroaccident.appear.dev-2/split_lib_slice_0_apk.apk)
                                                                                at droidninja.filepicker.adapters.FolderGridAdapter$PhotoViewHolder.<init>(FolderGridAdapter.java:136)
                                                                                at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:53)
                                                                                at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
                                                                                at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-16 10:06:40.717 21773-21773/se.euroaccident.appear.dev E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
                                                                                at android.view.View.layout(View.java:17689)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:241)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by DroidNinja** [comment]
Did you tried clean and rebuild?

**Comment by nick-kleban** [comment]
@DroidNinja Sure i used clean+build and 'git clean' for all untracked files, only thing that worked for me is adding to dependency to this library from master (via gitpack.io)

**Comment by nic003** [comment]
try this  compile 'com.droidninja:filepicker:2.0.8@aar'

**Comment by DroidNinja** [comment]
I dont know why is this thing happening? Can anybody tell me what is the root cause of this?

**Comment by nic003** [comment]
Im using 
compile 'com.droidninja:filepicker:2.0.8@aar' 
//GLIDE
compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
apt 'com.github.bumptech.glide:compiler:4.0.0-RC1'

**Comment by nick-kleban** [comment]
Let me check with @aar suffix.

**Comment by nick-kleban** [comment]
With @aar works, if i remove @aar - fails with the same error.

**Comment by nick-kleban** [comment]
Alright new update - seems adding @aar actually don't work. Previous time it worked because i just haven't cleared cache. Adding dependency with jitpack.io from git:master works fine. 

Devices:
Sony E6533 - Sony Xperia Z3+ dual (Android 7.1.1)
Samsung GT-I9100 (Android 4.1.2) 

`compile 'com.github.bumptech.glide:glide:4.0.0'`
 `compile 'com.github.bumptech.glide:annotations:4.0.0'`
`annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'`
`compile 'com.droidninja:filepicker:2.0.8@aar'`

`E/AndroidRuntime: FATAL EXCEPTION: main
                                     java.lang.NoSuchFieldError: droidninja.filepicker.R$id.iv_photo
                                         at droidninja.filepicker.adapters.FolderGridAdapter$PhotoViewHolder.<init>(FolderGridAdapter.java:136)
                                         at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:53)
                                         at droidninja.filepicker.adapters.FolderGridAdapter.onCreateViewHolder(FolderGridAdapter.java:24)
                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                         at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1644)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1428)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                         at android.view.View.layout(View.java:14072)
                                         at android.view.ViewGroup.layout(ViewGroup.java:4607)
                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1997)
                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1818)
                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4526)
                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                     	at android.view.Choreographe `
