### ISSUE TITLE
nullpointer exception in FolderGridAdapter

### ISSUE THREAD

**Issue by sandeepgahlawat** [DroidNinja/Android-FilePicker#88]
Hi, I am getting this error on some devices only ,please help.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.io.File.fixSlashes(File.java:183)
       at java.io.File.(File.java)
       at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:69)
       at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:22)
       at android.support.v7.widget.RecyclerView$Adapter.onCreateViewHolder(RecyclerView.java:6356)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3175)
       at android.view.View.layout(View.java:17995)
       at android.view.ViewGroup.layout(ViewGroup.java:5817)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2759)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7530)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:622)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7329)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by DroidNinja** [comment]
which devices?

**Comment by sandeepgahlawat** [comment]
Hi ,

Thanks for replying and It only occurs in Samsung devices.


Regards

**Comment by DroidNinja** [comment]
Is it occuring with latest version?

**Comment by alexkrol** [comment]
Hi @DroidNinja, I have the same problem... pure Android 7.1.2, Xiaomi Mi A1

**Comment by alexkrol** [comment]
...and it occurs only on `pickPhoto`, `pickFile` works well

**Comment by mahasadhu** [comment]
@DroidNinja I have some problem too, Asus with Android version 4

`Fatal Exception: java.lang.NullPointerException
       at java.io.File.fixSlashes(File.java:185)
       at java.io.File.<init>(File.java:134)
       at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:69)
       at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:22)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1330)
       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1074)
       at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4838)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:543)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by DroidNinja** [comment]
Ok I think this `fixSlashes` method in File class is culprit here. It is no more in latest `File` api. I have added null checks in the model classes. This should correct it.

**Comment by DroidNinja** [comment]
Guys could you confirm this bug is fixed with latest version? 2.0.9

**Comment by mahasadhu** [comment]
@DroidNinja I can't really test it since it appears randomly on some devices. So all I can do is just wait and see whether the error shows up again in crash reporting or not.
