### ISSUE TITLE
Error when an error when trying to use the fuctions

### ISSUE THREAD

**Issue by marvinmosa** [DroidNinja/Android-FilePicker#99]
Receving an error

`Process: au.com.serviceseeking.business.android, PID: 31062
                                                                                        android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                                            at droidninja.filepicker.adapters.PhotoGridAdapter.onCreateViewHolder(PhotoGridAdapter.java:42)
                                                                                            at droidninja.filepicker.adapters.PhotoGridAdapter.onCreateViewHolder(PhotoGridAdapter.java:24)
                                                                                            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                            at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1574)
                                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:684)
                                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:606)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                            at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3144)
                                                                                            at android.view.View.layout(View.java:17972)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2668)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2369)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1439)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7422)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                        	at android.view.Choreographer.doCallbacks(Choreographe`

**Comment by DroidNinja** [comment]
Are you sure you are using latest version of filepicker? Filepicker doesn't use fresco now.
